name: agent-run
on:
  issue_comment:
    types: [created]
permissions:
  issues: write
  contents: write
jobs:
  run:
    if: contains(github.event.comment.body, '/agent run')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Stub agent (demo)
        run: |
          num='${{ github.event.issue.number }}'
          mkdir -p docs/ISSUE-$num
          echo "# Demo summary for #$num" > docs/ISSUE-$num/summary.md
          git config user.name "agent-bot"
          git config user.email "bot@local"
          git add docs
          git commit -m "agent: summary for #$num" || true
          git push || true
      - name: Comment digest
        run: gh issue comment ${{ github.event.issue.number }} -b "✅ 要約を docs/ISSUE-${{ github.event.issue.number }}/summary.md に保存しました"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Ensure label (re-fire labeled)
        env:
          GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}   # PAT（scopes: repo, project）
        run: |
          gh issue edit ${{ github.event.issue.number }} --remove-label "stage:summary" || true
          gh issue edit ${{ github.event.issue.number }} --add-label "stage:summary"

